@extends('errors.minimal')
@section('title', 'درخواست‌های زیاد')
@section('code', '۴۲۹')
@section('heading', 'تعداد درخواست‌ها بیش از حد مجاز است')
@section('message', 'برای حفظ امنیت، تعداد تلاش‌ها محدود است. لطفا یک دقیقه صبر کنید و دوباره امتحان کنید.')
